#!/bin/bash
# Script to install and change permission of the ELE784-Lab1 module
# Usage ./script_lab1 [ --quit | --read | --write ]

if [ "$1" == "" ]; then
  make  
  sleep 10
	sudo insmod ./ele784-lab1.ko
	sudo chmod 666 /dev/etsele_cdev
  sudo gcc charDriverWrite.c -o write.out
  sudo gcc charDriverRead.c -o read.out
  sudo gcc charDriverIoctl.c -o ioctl.out
fi

while [ "$1" != "" ]; do
	case $1 in
		-q | --quit )	shift
				sudo rmmod ele784_lab1
				;;
		-r | --read )	shift
				sudo cat /dev/etsele_cdev
				;;
		-w | --write ) 	shift
				sudo echo "charDriver" > /dev/etsele_cdev
				;; 
	esac
done


